export { default as About } from './about/About';
export { default as Skills } from './skills/Skills';
export { default as Socials } from './socials/Socials';
export { default as Hero } from './hero/Hero';
export { default as Nav } from './nav/Nav';
export { default as Work } from './work/Work';
export { default as Contact } from './contact/Contact';
export { default as Footer } from './footer/Footer';
export { default as Projects } from './projects/Projects';
